# Site settings
baseurl = "" 
relativeurls = true
languageCode = "en"
title = "Cause for Concern"
theme = "hugo-theme-cactus-plus"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "Ángela Castillo-Gill"
	description = "A journey to understand causal inference and product management."
	bio = "A journey to understand causal inference and product management."

	twitter = "https://www.twitter.com/acastillogill"

	enableRSS = false
	enableToc = true

	enableDisqus = true

# Enable emoji
enableEmoji = true

# Enable comments by entering your Disqus shortname
disqusShortname = "https-acastillogill-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-128602464-1"

[permalinks]
    post = "/:year/:month/:slug"

    disable_mathjax = false # set to true to disable MathJax
	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = "© Copyright 2020 | Ángela Castillo-Gill"

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""

    highlightjsVersion = "9.14.2"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "atom-one-light"


 ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]