# Site settings
languageCode = "en"
title = "Cause for Concern"
theme = "hugo-theme-cactus-plus"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# baseurl = "https://acastillogill.com/"
relativeurls = true

[permalinks]
    post = "/:year/:month/:slug"

[params]
	author = "Ángela Castillo-Gill"
	description = "A journey to understand causal inference and product management."
	bio = "A journey to understand causal inference and product management."

	enableRSS = false
	enableToc = true

	enableDisqus = true

# Enable emoji
enableEmoji = true

# Enable comments by entering your Disqus shortname
disqusShortname = "https-acastillogill-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-128602464-1"


    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = ""
    logo = ""
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_js  = [""]

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"
    

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/acastillogill"



# options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.14.2"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "atom-one-light"

# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
footnoteanchorprefix = "°"

#  enable GDPR settings
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
